/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "Spy_FakeFunctionsToCall.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_FakeFunctionAtStart(void);
extern void test_FakeFunctionReturnsLastFuncCalled(void);
extern void test_FakeFunctionReturns0AfterRecreation(void);
extern void test_FakeFunctionClearsLastFunctionCalledOnceItIsRead(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/spy_fakefunctions/TestFakeFunctions.c");
  run_test(test_FakeFunctionAtStart, "test_FakeFunctionAtStart", 14);
  run_test(test_FakeFunctionReturnsLastFuncCalled, "test_FakeFunctionReturnsLastFuncCalled", 19);
  run_test(test_FakeFunctionReturns0AfterRecreation, "test_FakeFunctionReturns0AfterRecreation", 28);
  run_test(test_FakeFunctionClearsLastFunctionCalledOnceItIsRead, "test_FakeFunctionClearsLastFunctionCalledOnceItIsRead", 35);

  return UnityEnd();
}
